if (point_in_rectangle(mouse_x, mouse_y, 
      x - sprite_xoffset, y - sprite_yoffset, 
      x - sprite_xoffset + sprite_width, y - sprite_yoffset + sprite_height)) {
    if (mouse_check_button_pressed(mb_left)) {
	inventoryRemove(obj_inventory, 0)
	inventoryRemove(obj_inventory, 1)
	inventoryRemove(obj_inventory, 2)
	inventoryRemove(obj_inventory, 3)
	inventoryRemove(obj_inventory, 4)
	inventoryRemove(obj_inventory, 5)
	inventoryRemove(obj_inventory, 6)
	inventoryRemove(obj_inventory, 7)
	inventoryRemove(obj_inventory, 8)
	inventoryRemove(obj_inventory, 9)
	inventoryRemove(obj_inventory, 10)
	inventoryRemove(obj_inventory, 11)
	inventoryRemove(obj_inventory, 12)
	inventoryRemove(obj_inventory, 13)
	inventoryRemove(obj_inventory, 14)
	inventoryRemove(obj_inventory, 15)
	inventoryRemove(obj_inventory, 16)
	inventoryRemove(obj_inventory, 17)
	inventoryRemove(obj_inventory, 18)
	inventoryRemove(obj_inventory, 19)
	inventoryRemove(obj_inventory, 20)
	inventoryRemove(obj_inventory, 21)
	inventoryRemove(obj_inventory, 22)
	inventoryRemove(obj_inventory, 23)
	inventoryRemove(obj_inventory, 24)
	inventoryRemove(obj_inventory, 25)
	inventoryRemove(obj_inventory, 26)
	inventoryRemove(obj_inventory, 27)
	inventoryRemove(obj_inventory, 28)
	inventoryRemove(obj_inventory, 29)
	inventoryRemove(obj_inventory, 30)
	inventoryRemove(obj_inventory, 31)
	inventoryRemove(obj_inventory, 32)
	inventoryRemove(obj_inventory, 33)
	inventoryRemove(obj_inventory, 34)
	inventoryRemove(obj_inventory, 35)
	inventoryRemove(obj_inventory, 36)
	inventoryRemove(obj_inventory, 37)
	inventoryRemove(obj_inventory, 38)
	inventoryRemove(obj_inventory, 39)
	inventoryRemove(obj_inventory, 40)
	inventoryRemove(obj_inventory, 41)
	inventoryRemove(obj_inventory, 42)
	inventoryRemove(obj_inventory, 43)
	inventoryRemove(obj_inventory, 44)
	inventoryRemove(obj_inventory, 45)
	inventoryRemove(obj_inventory, 46)
	inventoryRemove(obj_inventory, 47)
	inventoryRemove(obj_inventory, 48)
	inventoryRemove(obj_inventory, 49)
  }
}